### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by michaeltryl** [nordicopen/easee_hass#404]
### The problem

I cant login to the integration it keep saying 
Unknown error occurred
I have tried with my phone number and email as user name

### Version of Easee integration having the issue?

Easee

### Version of Home Assistant Core having the issue?

Core 2024-3-3

**Comment by olalid** [comment]
Are you using the latest version? I.e. 0.9.58?
Can you check if there is anything in the logs?
Enabling debug logging might give additional clues, as stated in the readme you can add this to your configuration.yaml:
```
logger:
  default: info
  logs:
    pyeasee: debug
    custom_components.easee: debug
```
Also, you can test your login credentials by using them at https://easee.cloud to make sure they are working.
