### ISSUE TITLE
How to set the dynamic current limit?

### ISSUE THREAD

**Issue by ppuschmann** [nordicopen/easee_hass#427]
### Question

Hi there,

I want to use https://github.com/InventoCasa/ha-advanced-blueprints/tree/main/PV_Excess_Control to control my PV excess charging.
This automation basically sets the desired charging current (in limits of 6A to 16A) to some helper variable and uses `switch.<easee_id>_charger_enabled` to switch the wallbox on/off.

I don't like the use of `switch.<easee_id>_charger_enabled`, but it works.

I now would use a helper-automation to change the actual value in the Easee Wallbox.

I now wonder how I should actually set this current limit:

```yaml
alias: Wallbox Set Charging Current Limits
description: ""
trigger:
  - platform: state
    entity_id:
      - input_number.wallbox_strom_dynamisch # helper variable
  - platform: time_pattern
    minutes: "2"
condition:
  - condition: sun
    before: sunset
    after: sunrise
action:
  - service: easee.set_charger_dynamic_limit
    metadata: {}
    data:
      current: 616
      device_id: <my-device-id>
mode: single
```

This code was generate with the help of the UI.

I want to use 3 phases for charging.

Is then 
```yaml
action:
  - service: easee.set_charger_dynamic_limit
    metadata: {}
    data:
      current: 616
      device_id: <my-device-id>
```
correct, or is there something needed like

```yaml
action:
  - service: easee.set_charger_dynamic_limit
    metadata: {}
    data:
      current_P0: 6
      current_P1: 6
      current_P2: 6
      device_id: <my-device-id>
```

Reason for the question: https://developer.easee.com/reference/post_api-sites-siteid-circuits-circuitid-dynamiccurrent is about 3 different values and also the readme uses this in the example:

```yaml
service: easee.set_circuit_dynamic_limit
data:
  charger_id: EVK1234
  current_p1: 10
```

Yes, I know, that the current code examples use static values for the current.
I'd like to find out how I should set a dynamic current to the wallbox.

Thank you.

### What version of the integration are you using?

0.9.59

### Additional information

Maybe related: `sensor.<charger_id>_dynamic_charger_limit` is not available?
![image](https://github.com/nordicopen/easee_hass/assets/3431761/3034aad5-1195-4103-b19c-4c5a543c46ad)
