### ISSUE TITLE
No state_class attribute for entity sessionenergy

### ISSUE THREAD

**Issue by Bertk** [nordicopen/easee_hass#595]
### Before creating an issue...

- [x] There is no open issue describing the same problem
- [x] I am running latest versions of the integration and of Home Assistant
- [x] I have checked the operational status of the Easee API

### The problem

 Currently only `state.lifetimeEnergy` can be used with the **energy dashboard**. I tried to configure ‘state.sessionEnergy’ but this is not possible because the attribute state_class is not defined.

 `"state_class": SensorStateClass.TOTAL_INCREASING,`

![Image](https://github.com/user-attachments/assets/81a2bcc2-e3f4-46a9-ac25-41c86f87575d)

![Image](https://github.com/user-attachments/assets/a6e704a5-cba9-4a09-8dc2-4189c1bcdd75)

Entity for “Energy per day” would be nice.

### Version of Easee integration having the issue?

0.9.69

### Version of Home Assistant Core having the issue?

2025.2.5

### Anything in the logs that might be useful for us?

```txt

```

**Comment by olalid** [comment]
Sure, but why would you want to use the session energy sensor in the energy dashboard, it will reset back to 0 for each charging session which will give strange results in the energy dashboard.

**Comment by Bertk** [comment]
SessionEnergy has accurate time values. Energy dashboard calculates the consumption energy consumption every hour.

![Image](https://github.com/user-attachments/assets/5dc9ee0e-5140-4b49-ace4-f640384fd28f)

![Image](https://github.com/user-attachments/assets/426a21b3-5fa4-4611-85e0-77ddb5ee7363)

**Comment by Bertk** [comment]
I guess the update frequency for "lifetime_energy" is not sufficient and  "session_energy“ is a better choice.

![Image](https://github.com/user-attachments/assets/a3553731-abce-49d1-980f-c120cc8850d0)

**Comment by olalid** [comment]
It will not work as you expect since it does not make the last update until you unplug the car. So you will see some energy being consumed where the car is unplugged, even if it was actually consumed several hours earlier.
I.e. it is intentional that this sensor does not have the total_increasing flag.
If you want to have a sensor that will give you more correct results I would suggest you create an integration sensor using the power sensor as input.

**Comment by olalid** [comment]
Since adding total_increasing to the session_energy sensor is not really a good option I am closing this.
If you want to try it out you can always create a template sensor using it as input and set the total_increasing flag on that sensor.

**Comment by Bertk** [comment]
Fine with me. I use another template sensor which has the required state_class.

```
- trigger:
    - trigger: time_pattern
      minutes: /10
  sensor:
    # Add state_class für Wallbox "session_energy“
    - name: "E_wallbox_session"
      unique_id: "sensor.ehvucdqv_sitzungsenergie_derived"
      state_class: total_increasing
      icon: mdi:ev-station
      unit_of_measurement: kWh
      device_class: energy
      state: "{{states('sensor.ehvucdqv_sitzungsenergie')|float(0)}}"
      availability: "{{ has_value('sensor.ehvucdqv_sitzungsenergie') and states('sensor.ehvucdqv_sitzungsenergie')|is_number}}"
```
